CREATE TABLE USEER(
User_ID NUMBER PRIMARY KEY,
Name VARCHAR2(50),
Email VARCHAR2(50));

--ACCOUNT TABLE--
CREATE TABLE ACCOUNTS(
Account_ID NUMBER PRIMARY KEY,
User_ID NUMBER,
BALANCE NUMBER);

--TRANSACTION TABLE--
CREATE TABLE TRANSACTIONS(
Txn_ID NUMBER PRIMARY KEY,
Account_ID NUMBER,
AMOUNT NUMBER,
TXN_TYPE VARCHAR2(10),
CATEGORY VARCHAR2(20),
TXN_DATE DATE,
Risk_Flag VARCHAR2(10)
);
