--USER TABLE--
CREATE TABLE USEER(
User_ID NUMBER PRIMARY KEY,
Name VARCHAR2(50),
Email VARCHAR2(50));

--ACCOUNT TABLE--
CREATE TABLE ACCOUNTS(
Account_ID NUMBER PRIMARY KEY,
User_ID NUMBER,
BALANCE NUMBER);

--TRANSACTION TABLE--
CREATE TABLE TRANSACTIONS(
Txn_ID NUMBER PRIMARY KEY,
Account_ID NUMBER,
AMOUNT NUMBER,
TXN_TYPE VARCHAR2(10),
CATEGORY VARCHAR2(20),
TXN_DATE DATE,
Risk_Flag VARCHAR2(10)
);

--INSERTION IN TABLE--
INSERT INTO useer VALUES(1,'Shradha','shra78@gmail.com');
INSERT INTO useer VALUES(2,'Karthik','kar12@gmail.com');
INSERT INTO useer VALUES(3,'Rohini','rooh8@gmail.com');
INSERT INTO useer VALUES(4,'Sarthak','sar88@gmail.com');

INSERT INTO accounts VALUES (101,1,457466);
INSERT INTO accounts VALUES (102,2,780045);
INSERT INTO accounts VALUES (103,3,365184);
INSERT INTO accounts VALUES (104,4,4875256);

INSERT INTO transactions VALUES(401,101,5000,'DEBIT','FOOD',SYSDATE,NULL);
INSERT INTO transactions VALUES(402,102,10000,'DEBIT','SHOPPING',SYSDATE,NULL);
INSERT INTO transactions VALUES(403,103,50000,'DEBIT','TRAVEL',SYSDATE,NULL);
INSERT INTO transactions VALUES(405,104,54488,'DEBIT','FOOD',SYSDATE,NULL);


SELECT *FROM useer;

SELECT *FROM accounts;

DELETE FROM transactions
WHERE Txn_ID = 403;

SELECT * FROM transactions;
SELECT Txn_ID FROM TRANSACTIONS;

--FOREIGN KEY--
ALTER TABLE ACCOUNTS ADD CONSTRAINT fk_USEER FOREIGN KEY (User_ID) REFERENCES USEER(User_ID);

ALTER TABLE TRANSACTIONS ADD CONSTRAINT fk_ACCOUNTS FOREIGN KEY (Account_ID) REFERENCES ACCOUNTS(Account_ID);

--JOIN--
--LET'S GET USER NAME , TRANSACTION AMOUNT AND CATEGORY--
SELECT u.Name, t.AMOUNT, t.CATEGORY
FROM useer u
JOIN accounts a ON u.user_id=a.user_id
JOIN transactions t ON a.account_id=t.account_id;

--LET'S SEE USER NAME + BALANCE--
SELECT u.Name , a.BALANCE
FROM useer u
JOIN accounts a ON u.user_id=a.user_id;

--CATEGORY-WISE SPENDING--
SELECT CATEGORY , SUM(AMOUNT) AS TOTAL_SPENDING
FROM TRANSACTIONS
GROUP BY CATEGORY;

--TOTAL SPENDING PER ACCOUNT--
SELECT Account_ID, SUM(AMOUNT) AS TOTAL
FROM transactions
GROUP BY Account_ID;

--HIGHEST SPENDING FIRST--
SELECT Account_ID, SUM(AMOUNT) AS TOTAL
FROM transactions
GROUP BY Account_ID
ORDER BY TOTAL DESC;

--MONTHLY SPENDING--
SELECT TO_CHAR(TXN_DATE,'MM-YYYY')AS MONTH,
SUM(AMOUNT) FROM transactions
GROUP BY TO_CHAR(TXN_DATE,'MM-YYYY');

--category has highest spending--
SELECT CATEGORY , SUM(AMOUNT) AS TOTAL_SPENDING
FROM TRANSACTIONS
GROUP BY CATEGORY
ORDER BY SUM(AMOUNT) DESC;

--only spending > 5000 total--
SELECT CATEGORY , SUM(AMOUNT) AS TOTAL_SPENDING
FROM TRANSACTIONS
GROUP BY CATEGORY
HAVING SUM(AMOUNT)>5000;

--PL/SQL PROCEDURE--
CREATE OR REPLACE PROCEDURE DETECT_RISK
IS
BEGIN

UPDATE TRANSACTIONS
SET risk_flag='HIGH'
WHERE amount>10000;

COMMIT;
END;
/

--RUN PROCEDUR--
BEGIN
DETECT_RISK;
END;
/

SELECT *FROM transactions;